## Preprocessing

In [36]:
! pip install pyyaml h5py

Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (6.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (3.8.0)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.10/dist-packages (from h5py) (1.22.4)

In [24]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import tensorflow.keras as keras

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_Type_counts = application_df['APPLICATION_TYPE'].value_counts()
app_Type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_Type_counts[app_Type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
greater_1_count = class_counts.loc[class_counts > 1]
greater_1_count.head()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [25]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies  = pd.get_dummies(application_df)

In [26]:
application_dummies .sample(10)

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
24295,721427569,1,8181,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
9307,310925677,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1202,200622700,1,172372,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
17959,472039844,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
539,50544491,1,13201,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
10833,364660842,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17726,471613530,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12586,452038553,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19172,474527917,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5919,263568515,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop(['IS_SUCCESSFUL'], axis=1)
y = application_dummies['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=47)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
!pip install keras-tuner --upgrade

Collecting keras-tuner
  Downloading keras_tuner-1.3.5-py3-none-any.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (23.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.27.1)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.4)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.3.5 kt-legacy-1.0.5

In [29]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="relu"))

# Output layer(sigmoid because it's binary classifier))
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                440

 dense_4 (Dense)             (None, 5)                 55

 dense_5 (Dense)             (None, 1)                 6

=================================================================
Total params: 501
Trainable params: 501
Non-trainable params: 0
_________________________________________________________________

In [37]:
import os
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint_path = "training_1/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)

In [39]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100,callbacks=[cp_callback])

Epoch 1/100
793/804 [============================>.] - ETA: 0s - loss: 0.5419 - accuracy: 0.7368
Epoch 1: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 3ms/step - loss: 0.5420 - accuracy: 0.7367
Epoch 2/100
804/804 [==============================] - ETA: 0s - loss: 0.5418 - accuracy: 0.7373
Epoch 2: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7373
Epoch 3/100
794/804 [============================>.] - ETA: 0s - loss: 0.5421 - accuracy: 0.7368
Epoch 3: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7370
Epoch 4/100
786/804 [============================>.] - ETA: 0s - loss: 0.5419 - accuracy: 0.7369
Epoch 4: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7374
Epoch 5/100
784/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7376
Epoch 5: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7370
Epoch 6/100
793/804 [============================>.] - ETA: 0s - loss: 0.5414 - accuracy: 0.7372
Epoch 6: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7374
Epoch 7/100
798/804 [============================>.] - ETA: 0s - loss: 0.5417 - accuracy: 0.7361
Epoch 7: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7362
Epoch 8/100
792/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7377
Epoch 8: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7371
Epoch 9/100
792/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7370
Epoch 9: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7370
Epoch 10/100
801/804 [============================>.] - ETA: 0s - loss: 0.5414 - accuracy: 0.7382
Epoch 10: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7378
Epoch 11/100
793/804 [============================>.] - ETA: 0s - loss: 0.5419 - accuracy: 0.7367
Epoch 11: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7369
Epoch 12/100
802/804 [============================>.] - ETA: 0s - loss: 0.5416 - accuracy: 0.7373
Epoch 12: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7372
Epoch 13/100
800/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7373
Epoch 13: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7370
Epoch 14/100
804/804 [==============================] - ETA: 0s - loss: 0.5415 - accuracy: 0.7371
Epoch 14: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7371
Epoch 15/100
790/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7366
Epoch 15: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7366
Epoch 16/100
797/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7370
Epoch 16: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7369
Epoch 17/100
787/804 [============================>.] - ETA: 0s - loss: 0.5416 - accuracy: 0.7367
Epoch 17: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7370
Epoch 18/100
790/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7370
Epoch 18: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7371
Epoch 19/100
796/804 [============================>.] - ETA: 0s - loss: 0.5414 - accuracy: 0.7371
Epoch 19: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7371
Epoch 20/100
791/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7369
Epoch 20: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7369
Epoch 21/100
787/804 [============================>.] - ETA: 0s - loss: 0.5417 - accuracy: 0.7370
Epoch 21: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7373
Epoch 22/100
791/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7377
Epoch 22: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7373
Epoch 23/100
797/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7375
Epoch 23: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7372
Epoch 24/100
792/804 [============================>.] - ETA: 0s - loss: 0.5417 - accuracy: 0.7365
Epoch 24: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7368
Epoch 25/100
792/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7375
Epoch 25: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7374
Epoch 26/100
800/804 [============================>.] - ETA: 0s - loss: 0.5413 - accuracy: 0.7374
Epoch 26: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 3ms/step - loss: 0.5412 - accuracy: 0.7374
Epoch 27/100
783/804 [============================>.] - ETA: 0s - loss: 0.5423 - accuracy: 0.7371
Epoch 27: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7379
Epoch 28/100
788/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7376
Epoch 28: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7375
Epoch 29/100
796/804 [============================>.] - ETA: 0s - loss: 0.5403 - accuracy: 0.7382
Epoch 29: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7376
Epoch 30/100
788/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7370
Epoch 30: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7370
Epoch 31/100
779/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7380
Epoch 31: saving model to training_1/cp.ckpt
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7373
Epoch 32/100
795/804 [============================>.] - ETA: 0s - loss: 0.5414 - accuracy: 0.7366
Epoch 32: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7366
Epoch 33/100
789/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7368
Epoch 33: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7367
Epoch 34/100
797/804 [============================>.] - ETA: 0s - loss: 0.5408 - accuracy: 0.7379
Epoch 34: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7376
Epoch 35/100
803/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7370
Epoch 35: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7371
Epoch 36/100
791/804 [============================>.] - ETA: 0s - loss: 0.5413 - accuracy: 0.7373
Epoch 36: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7373
Epoch 37/100
794/804 [============================>.] - ETA: 0s - loss: 0.5402 - accuracy: 0.7381
Epoch 37: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7378
Epoch 38/100
786/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7367
Epoch 38: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7371
Epoch 39/100
787/804 [============================>.] - ETA: 0s - loss: 0.5409 - accuracy: 0.7383
Epoch 39: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7378
Epoch 40/100
791/804 [============================>.] - ETA: 0s - loss: 0.5413 - accuracy: 0.7371
Epoch 40: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7374
Epoch 41/100
803/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7383
Epoch 41: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7381
Epoch 42/100
791/804 [============================>.] - ETA: 0s - loss: 0.5417 - accuracy: 0.7364
Epoch 42: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7369
Epoch 43/100
786/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7377
Epoch 43: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7376
Epoch 44/100
785/804 [============================>.] - ETA: 0s - loss: 0.5408 - accuracy: 0.7378
Epoch 44: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7373
Epoch 45/100
793/804 [============================>.] - ETA: 0s - loss: 0.5414 - accuracy: 0.7371
Epoch 45: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7376
Epoch 46/100
804/804 [==============================] - ETA: 0s - loss: 0.5412 - accuracy: 0.7367
Epoch 46: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7367
Epoch 47/100
801/804 [============================>.] - ETA: 0s - loss: 0.5409 - accuracy: 0.7370
Epoch 47: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7371
Epoch 48/100
781/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7373
Epoch 48: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7378
Epoch 49/100
797/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7372
Epoch 49: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7374
Epoch 50/100
779/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7368
Epoch 50: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7367
Epoch 51/100
801/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7370
Epoch 51: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7371
Epoch 52/100
797/804 [============================>.] - ETA: 0s - loss: 0.5410 - accuracy: 0.7378
Epoch 52: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7378
Epoch 53/100
791/804 [============================>.] - ETA: 0s - loss: 0.5406 - accuracy: 0.7377
Epoch 53: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7375
Epoch 54/100
797/804 [============================>.] - ETA: 0s - loss: 0.5408 - accuracy: 0.7374
Epoch 54: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 55/100
799/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7380
Epoch 55: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7376
Epoch 56/100
797/804 [============================>.] - ETA: 0s - loss: 0.5409 - accuracy: 0.7371
Epoch 56: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7374
Epoch 57/100
803/804 [============================>.] - ETA: 0s - loss: 0.5408 - accuracy: 0.7377
Epoch 57: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 4ms/step - loss: 0.5408 - accuracy: 0.7376
Epoch 58/100
779/804 [============================>.] - ETA: 0s - loss: 0.5406 - accuracy: 0.7374
Epoch 58: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7374
Epoch 59/100
792/804 [============================>.] - ETA: 0s - loss: 0.5402 - accuracy: 0.7376
Epoch 59: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 60/100
777/804 [===========================>..] - ETA: 0s - loss: 0.5409 - accuracy: 0.7375
Epoch 60: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7376
Epoch 61/100
788/804 [============================>.] - ETA: 0s - loss: 0.5419 - accuracy: 0.7357
Epoch 61: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7371
Epoch 62/100
803/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7375
Epoch 62: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7375
Epoch 63/100
788/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7367
Epoch 63: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7370
Epoch 64/100
796/804 [============================>.] - ETA: 0s - loss: 0.5402 - accuracy: 0.7376
Epoch 64: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7373
Epoch 65/100
788/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7378
Epoch 65: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7382
Epoch 66/100
803/804 [============================>.] - ETA: 0s - loss: 0.5406 - accuracy: 0.7370
Epoch 66: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7369
Epoch 67/100
789/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7365
Epoch 67: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7371
Epoch 68/100
799/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7372
Epoch 68: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7373
Epoch 69/100
782/804 [============================>.] - ETA: 0s - loss: 0.5404 - accuracy: 0.7381
Epoch 69: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7380
Epoch 70/100
794/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7376
Epoch 70: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 3ms/step - loss: 0.5405 - accuracy: 0.7376
Epoch 71/100
797/804 [============================>.] - ETA: 0s - loss: 0.5404 - accuracy: 0.7377
Epoch 71: saving model to training_1/cp.ckpt
804/804 [==============================] - 5s 6ms/step - loss: 0.5403 - accuracy: 0.7377
Epoch 72/100
789/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7366
Epoch 72: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7369
Epoch 73/100
789/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7376
Epoch 73: saving model to training_1/cp.ckpt
804/804 [==============================] - 3s 3ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 74/100
789/804 [============================>.] - ETA: 0s - loss: 0.5406 - accuracy: 0.7371
Epoch 74: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 75/100
788/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7371
Epoch 75: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7370
Epoch 76/100
788/804 [============================>.] - ETA: 0s - loss: 0.5409 - accuracy: 0.7370
Epoch 76: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7372
Epoch 77/100
789/804 [============================>.] - ETA: 0s - loss: 0.5414 - accuracy: 0.7368
Epoch 77: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7374
Epoch 78/100
802/804 [============================>.] - ETA: 0s - loss: 0.5403 - accuracy: 0.7374
Epoch 78: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7374
Epoch 79/100
779/804 [============================>.] - ETA: 0s - loss: 0.5408 - accuracy: 0.7367
Epoch 79: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7370
Epoch 80/100
802/804 [============================>.] - ETA: 0s - loss: 0.5405 - accuracy: 0.7372
Epoch 80: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7372
Epoch 81/100
785/804 [============================>.] - ETA: 0s - loss: 0.5411 - accuracy: 0.7370
Epoch 81: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7378
Epoch 82/100
788/804 [============================>.] - ETA: 0s - loss: 0.5406 - accuracy: 0.7383
Epoch 82: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7384
Epoch 83/100
797/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7375
Epoch 83: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7374
Epoch 84/100
801/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7377
Epoch 84: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7378
Epoch 85/100
786/804 [============================>.] - ETA: 0s - loss: 0.5412 - accuracy: 0.7371
Epoch 85: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7376
Epoch 86/100
802/804 [============================>.] - ETA: 0s - loss: 0.5403 - accuracy: 0.7376
Epoch 86: saving model to training_1/cp.ckpt
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7376
Epoch 87/100

In [41]:
os.listdir(checkpoint_dir)

['checkpoint', 'cp.ckpt.index', 'cp.ckpt.data-00000-of-00001']

In [42]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5524 - accuracy: 0.7311 - 477ms/epoch - 2ms/step
Loss: 0.5523868799209595, Accuracy: 0.7310787439346313

In [44]:
# Export our model to HDF5 file  AlphabetSoupCharity
nn.save("/Users/ritta/Documents/bootcamp/deep-learning-challenge/Starter_Code/HDF5/AlphabetSoupCharity.h5")